[package]
name = "dbx_download"
version = "0.1.0"
authors = ["Luciano Bestia <LucianoBestia@gmail.com>"]
edition = "2018"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[profile.release]
#lto = "thin"
#panic = "abort"
#opt-level = "s"

[dependencies]
env_logger = "0.7.1"
chrono = "0.4.15"
unwrap="1.2.1"
lexical-sort = "0.3.1"
# colorful output to screen
ansi_term = "0.12.1"
walkdir = "2.3.1"
filetime = "0.2"
humantime="2.1.0"

[dependencies.dropbox-sdk]
version = "0.5.0"
default_features = false
features = ["dbx_files", "hyper_client"]