[package]
name = "dropbox_backup_to_external_disk"
version = "0.1.85"
description = "one way sync from dropbox to an external disc"
authors = ["Luciano Bestia <LucianoBestia@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucianobestia/dropbox_backup_to_external_disk/"
categories = ["programming"]
keywords = ["dropbox"]
publish = false

[dependencies]
env_logger = "0.9.0"
chrono = "0.4.15"
unwrap = "1.2.1"
# colorful output to screen
ansi_term = "0.12.1"
walkdir = "2.3.1"
filetime = "0.2"
humantime = "2.1.0"
rayon = "1.5.1"
uncased = "0.9"
term_cursor = "0.2.1"

[dependencies.dropbox-sdk]
version = "0.11.3"
default_features = false
features = ["dbx_files", "default_client"]
